let buildings = {
  "data": [
    {
      "buildingCode": "ALU",
      "buildingName": "Alumni Hall",
      "buildingAddress": "350 EAST SPRING STREET",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50789683",
      "longitude": "-84.7364642",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/alu.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "BEN",
      "buildingName": "Benton Hall",
      "buildingAddress": "510 EAST HIGH STREET",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.51074101",
      "longitude": "-84.7335931",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/ben.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "HAL",
      "buildingName": "Hall Auditorium",
      "buildingAddress": "101 SOUTH CAMPUS AVENUE",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50896457",
      "longitude": "-84.73857386",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/hal.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "CUL"
    },
    {
      "buildingCode": "LWS",
      "buildingName": "Laws Hall",
      "buildingAddress": "551 EAST HIGH STREET",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50971861",
      "longitude": "-84.73319022",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/lws.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "BAC",
      "buildingName": "Bachelor Hall",
      "buildingAddress": "301 SOUTH PATTERSON AVENUE",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50719607",
      "longitude": "-84.72965229",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/bac.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "OMN",
      "buildingName": "Old Manse",
      "buildingAddress": "410 EAST HIGH STREET",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.51071493",
      "longitude": "-84.73545213",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/omn.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ADM"
    },
    {
      "buildingCode": "GRD",
      "buildingName": "Gardner-Harvey Library",
      "buildingAddress": "4200 North University Boulevard Building",
      "buildingCity": "Middletown",
      "buildingZip": "45042",
      "buildingState": null,
      "campusCode": "M",
      "latitude": "39.524692",
      "longitude": "-84.35704",
      "iconURL": null,
      "imageURL": null,
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "VER",
      "buildingName": "Verity Lodge",
      "buildingAddress": "4200 North University Boulevard Building",
      "buildingCity": "Middletown",
      "buildingZip": "45042",
      "buildingState": null,
      "campusCode": "M",
      "latitude": "39.525743",
      "longitude": "-84.356493",
      "iconURL": null,
      "imageURL": null,
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "CUL"
    },
    {
      "buildingCode": "MOS",
      "buildingName": "Mosler Hall",
      "buildingAddress": null,
      "buildingCity": null,
      "buildingZip": "45011",
      "buildingState": null,
      "campusCode": "H",
      "latitude": "39.377435",
      "longitude": "-84.563366",
      "iconURL": null,
      "imageURL": null,
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "DOR",
      "buildingName": "Dorsey Hall",
      "buildingAddress": "Dorsey Hall, Miami University, 900 East High Street",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.51067991",
      "longitude": "-84.72844836",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/dor.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "DOD",
      "buildingName": "Dodds Hall",
      "buildingAddress": "Dodds Hall, Miami University, 600 S Maple Avenue",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50310752",
      "longitude": "-84.733734",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/dod.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "DEN",
      "buildingName": "Dennison Hall",
      "buildingAddress": "Dennison Hall, Miami University, 21 Fisher Drive",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.51116988",
      "longitude": "-84.72616776",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/den.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "LYN",
      "buildingName": "Mary Lyon Hall",
      "buildingAddress": "Mary Lyon Hall, Miami University, 500 Western College Circle",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50390642",
      "longitude": "-84.72758289",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/lyn.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "MCF",
      "buildingName": "McFarland Hall",
      "buildingAddress": "McFarland Hall, Miami University, 325 Tallawanda Road",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.51404811",
      "longitude": "-84.73394163",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/mcf.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "MCK",
      "buildingName": "McKee Hall",
      "buildingAddress": "McKee Hall, Miami University, 600 Western College Drive",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50303377",
      "longitude": "-84.72628323",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/mck.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "MOR",
      "buildingName": "Morris Hall",
      "buildingAddress": "Morris Hall, Miami University, 651 S Maple Avenue",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50258697",
      "longitude": "-84.73246104",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/mor.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "POR",
      "buildingName": "Porter Hall",
      "buildingAddress": "Porter Hall, Miami University, 601 South Oak Street",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.5031169",
      "longitude": "-84.73560495",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/por.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "STD",
      "buildingName": "Stoddard Hall",
      "buildingAddress": "Stoddard Hall, Miami University, 201 Irvin Drive",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50849004",
      "longitude": "-84.73529933",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/std.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "SYM",
      "buildingName": "Symmes Hall",
      "buildingAddress": "Symmes Hall, Miami University, 500 Fisher Drive",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.5120649",
      "longitude": "-84.72935975",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/sym.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "WEL",
      "buildingName": "Wells Hall",
      "buildingAddress": "Wells Hall, Miami University, 301 East Spring Street",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50684269",
      "longitude": "-84.73749824",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/wel.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "EDH",
      "buildingName": "Erickson Dining Hall",
      "buildingAddress": "23 NORTH FISHER DRIVE",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.51114489",
      "longitude": "-84.72579071",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/edh.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "DIN"
    },
    {
      "buildingCode": "LEW",
      "buildingName": "Lewis Place",
      "buildingAddress": "310 EAST HIGH STREET",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.5107309",
      "longitude": "-84.73687929",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/lew.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ADM"
    },
    {
      "buildingCode": "UHH",
      "buildingName": "University Hall",
      "buildingAddress": null,
      "buildingCity": null,
      "buildingZip": "45011",
      "buildingState": null,
      "campusCode": "H",
      "latitude": "39.383757",
      "longitude": "-84.561934",
      "iconURL": null,
      "imageURL": null,
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "EGB",
      "buildingName": "Engineering Building",
      "buildingAddress": "650 EAST HIGH STREET",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.51071775",
      "longitude": "-84.73258237",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/egb.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "GRG",
      "buildingName": "Campus Avenue Garage",
      "buildingAddress": "601 SOUTH CAMPUS AVE.",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50375899",
      "longitude": "-84.73881301",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/grg.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ADM"
    },
    {
      "buildingCode": "GCB",
      "buildingName": "Glos Center",
      "buildingAddress": "820 SOUTH PATTERSON AVENUE",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50094813",
      "longitude": "-84.73149029",
      "iconURL": null,
      "imageURL": null,
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ADM"
    },
    {
      "buildingCode": "WTH",
      "buildingName": "Withrow Hall",
      "buildingAddress": "201 TALLAWANDA AVENUE",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.51248241",
      "longitude": "-84.73410833",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/wth.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ATH"
    },
    {
      "buildingCode": "ART",
      "buildingName": "Art Building",
      "buildingAddress": "400 SOUTH PATTERSON AVENUE",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50569746",
      "longitude": "-84.73131631",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/art.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "KRG",
      "buildingName": "Kreger Hall",
      "buildingAddress": "500 EAST SPRING STREET",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50798527",
      "longitude": "-84.73457707",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/krg.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "MCG",
      "buildingName": "McGuffey Hall",
      "buildingAddress": "210 EAST SPRING STREET",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50785102",
      "longitude": "-84.73832324",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/mcg.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "UPH",
      "buildingName": "Upham Hall",
      "buildingAddress": "100 BISHOP CIRCLE",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50873358",
      "longitude": "-84.73372414",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/uph.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "AMU",
      "buildingName": "Art Museum",
      "buildingAddress": "801 SOUTH PATTERSON AVENUE",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50093469",
      "longitude": "-84.72924761",
      "iconURL": null,
      "imageURL": null,
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "CUL"
    },
    {
      "buildingCode": "KNG",
      "buildingName": "King Library",
      "buildingAddress": "151 SOUTH CAMPUS AVENUE",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50881452",
      "longitude": "-84.73801745",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/kng.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "RSC",
      "buildingName": "Rec Sports Center",
      "buildingAddress": "750 SOUTH OAK STREET",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50265794",
      "longitude": "-84.73793412",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/rsc.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ATH"
    },
    {
      "buildingCode": "WIH",
      "buildingName": "Williams-Radio & TV",
      "buildingAddress": "350 SOUTH OAK STREET",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50644994",
      "longitude": "-84.73673408",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/wih.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "THH",
      "buildingName": "Thesken Hall",
      "buildingAddress": "4200 North University Boulevard Building",
      "buildingCity": null,
      "buildingZip": "45042",
      "buildingState": null,
      "campusCode": "M",
      "latitude": "39.524361",
      "longitude": "-84.359025",
      "iconURL": null,
      "imageURL": null,
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "HAV",
      "buildingName": "Havighurst Hall",
      "buildingAddress": "Havighurst Hall, Miami University, 350 Western College Drive",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50527976",
      "longitude": "-84.72724886",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/hav.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "ALX",
      "buildingName": "Alexander Dining Hall",
      "buildingAddress": "420 WESTERN COLLEGE DRIVE",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50429411",
      "longitude": "-84.72690963",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/alx.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "DIN"
    },
    {
      "buildingCode": "BON",
      "buildingName": "Bonham House",
      "buildingAddress": "351 EAST SPRING STREET",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50696627",
      "longitude": "-84.73650228",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/bon.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ADM"
    },
    {
      "buildingCode": "MMU",
      "buildingName": "McGuffey Museum",
      "buildingAddress": "410 EAST SPRING STREET",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.5069805",
      "longitude": "-84.73593092",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/mmu.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "CUL"
    },
    {
      "buildingCode": "TSN",
      "buildingName": "Tennis Storage - North",
      "buildingAddress": "425 WESTERN COLLEGE DRIVE",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50461373",
      "longitude": "-84.72504209",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/tsn.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "HCF",
      "buildingName": "Fisher Hall",
      "buildingAddress": "Fisher Hall, Miami University, 805 S Oak Street",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50150155",
      "longitude": "-84.7382584",
      "iconURL": null,
      "imageURL": null,
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "HIS",
      "buildingName": "Hiestand Hall",
      "buildingAddress": "401 MAPLE AVENUE",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.5055807",
      "longitude": "-84.73251364",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/his.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "LVH",
      "buildingName": "Levey Hall",
      "buildingAddress": "4200 North University Boulevard Building",
      "buildingCity": "Middletown",
      "buildingZip": "45042",
      "buildingState": null,
      "campusCode": "M",
      "latitude": "39.524361",
      "longitude": "-84.358145",
      "iconURL": null,
      "imageURL": null,
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "REN",
      "buildingName": "Rentschler",
      "buildingAddress": null,
      "buildingCity": null,
      "buildingZip": "45011",
      "buildingState": null,
      "campusCode": "H",
      "latitude": "39.377427",
      "longitude": "-84.562658",
      "iconURL": null,
      "imageURL": null,
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ADM"
    },
    {
      "buildingCode": "MIN",
      "buildingName": "Minnich Hall",
      "buildingAddress": "Minnich Hall, Miami University, 400 S Maple Avenue",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50560897",
      "longitude": "-84.73366939",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/min.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "HAM",
      "buildingName": "Hamilton Hall",
      "buildingAddress": "Hamilton Hall, Miami University, 401 South Oak Street",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50565519",
      "longitude": "-84.73554548",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/ham.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "TAP",
      "buildingName": "Tappan Hall",
      "buildingAddress": "Tappan Hall, Miami University, 650 South Patterson Avenue",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50258283",
      "longitude": "-84.73149728",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/tap.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "WIL",
      "buildingName": "Wilson Hall",
      "buildingAddress": "Wilson Hall, Miami University, 21 S Fisher Drive",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.51002383",
      "longitude": "-84.72662323",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/wil.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "VOA",
      "buildingName": "VOA West Chester",
      "buildingAddress": null,
      "buildingCity": null,
      "buildingZip": "45069",
      "buildingState": null,
      "campusCode": "V",
      "latitude": "39.360718",
      "longitude": "-84.362925",
      "iconURL": null,
      "imageURL": null,
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "BIL",
      "buildingName": "Billings Natatorium",
      "buildingAddress": "289 TALLAWANDA AVENUE",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.5135148",
      "longitude": "-84.73412044",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/bil.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "SHH",
      "buildingName": "Simpson Guest House",
      "buildingAddress": "300 EAST HIGH STREET",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.51066296",
      "longitude": "-84.73738256",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/shh.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ADM"
    },
    {
      "buildingCode": "CON",
      "buildingName": "Conservatory",
      "buildingAddress": null,
      "buildingCity": null,
      "buildingZip": "45011",
      "buildingState": null,
      "campusCode": "H",
      "latitude": "39.377477",
      "longitude": "-84.563865",
      "iconURL": null,
      "imageURL": null,
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "HCB",
      "buildingName": "Blanchard House",
      "buildingAddress": "Blanchard House, Miami University, 805 South Campus Avenue",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50092658",
      "longitude": "-84.73913725",
      "iconURL": null,
      "imageURL": null,
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "HCL",
      "buildingName": "Logan Lodge",
      "buildingAddress": "Logan Lodge, Miami University, 800 South Campus Avenue",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50151623",
      "longitude": "-84.73774729",
      "iconURL": null,
      "imageURL": null,
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "HCP",
      "buildingName": "Pines Lodge",
      "buildingAddress": "Pines Lodge, Miami University, 803 South Campus Avenue",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50090195",
      "longitude": "-84.73859937",
      "iconURL": null,
      "imageURL": null,
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "PSYC",
      "buildingName": "Psychology Building",
      "buildingAddress": "90 NORTH PATTERSON AVE.",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.51183799",
      "longitude": "-84.73143731",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/psyc.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "CSC",
      "buildingName": "Culinary Support Center",
      "buildingAddress": "426 WELLS MILL DRIVE",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50593313",
      "longitude": "-84.75196154",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/csc.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ADM"
    },
    {
      "buildingCode": "INN",
      "buildingName": "The Inn",
      "buildingAddress": "The Inn, Miami University, 300 North Patterson Avenue",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.51333554",
      "longitude": "-84.73100656",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/inn.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "CUL"
    },
    {
      "buildingCode": "HRN",
      "buildingName": "Harrison Hall",
      "buildingAddress": "349 EAST HIGH STREET",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50903034",
      "longitude": "-84.73645017",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/hrn.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "KUM",
      "buildingName": "Kumler Memorial Chapel",
      "buildingAddress": "650 WESTERN COLLEGE DRIVE",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50218504",
      "longitude": "-84.72638139",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/kum.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "CUL"
    },
    {
      "buildingCode": "MIL",
      "buildingName": "Millett Assembly Hall",
      "buildingAddress": "500 EAST SYCAMORE STREET",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.51724627",
      "longitude": "-84.73463322",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/mil.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ATH"
    },
    {
      "buildingCode": "ROW",
      "buildingName": "Rowan Hall",
      "buildingAddress": "550 EAST SPRING STREET",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50751475",
      "longitude": "-84.73313949",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/row.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "COL",
      "buildingName": "Collins Hall",
      "buildingAddress": "Collins Hall, Miami University, 31 Fisher Drive",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.51168742",
      "longitude": "-84.72701602",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/col.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "OGN",
      "buildingName": "Ogden Hall",
      "buildingAddress": "Ogden Hall, Miami University, 401 East High Street",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50978137",
      "longitude": "-84.73581184",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/ogn.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "STN",
      "buildingName": "Stanton Hall",
      "buildingAddress": "Stanton Hall, Miami University, 700 S Maple Avenue",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50209578",
      "longitude": "-84.73378451",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/stn.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "WAR",
      "buildingName": "Warfield Hall",
      "buildingAddress": "451 EAST SPRING STREET",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50692772",
      "longitude": "-84.73520852",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/war.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ADM"
    },
    {
      "buildingCode": "AIR",
      "buildingName": "Airport Metal Hangar",
      "buildingAddress": "7101 FAIRFIELD ROAD",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50723738",
      "longitude": "-84.78302584",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/air.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ADM"
    },
    {
      "buildingCode": "ALX",
      "buildingName": "Alexander Dining Hall",
      "buildingAddress": "420 WESTERN COLLEGE DRIVE",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50429411",
      "longitude": "-84.72690963",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/alx.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "LNS",
      "buildingName": "Western Lodge",
      "buildingAddress": "801 WESTERN COLLEGE DRIVE",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50016487",
      "longitude": "-84.72621242",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/lns.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "CUL"
    },
    {
      "buildingCode": "YGA",
      "buildingName": "Yager Gatehouse A",
      "buildingAddress": "5300 BONHAM ROAD",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.5195197",
      "longitude": "-84.73291275",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/yga.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ATH"
    },
    {
      "buildingCode": "HCR",
      "buildingName": "Reid Hall",
      "buildingAddress": "Reid Hall, Miami University, 806 South Oak Street",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.5008764",
      "longitude": "-84.73667066",
      "iconURL": null,
      "imageURL": null,
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "HCT",
      "buildingName": "Tallawanda Hall",
      "buildingAddress": "Tallawanda Hall, Miami University, 804 South Oak Street",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50089065",
      "longitude": "-84.73746248",
      "iconURL": null,
      "imageURL": null,
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "MUR",
      "buildingName": "Murstein Alumni Center",
      "buildingAddress": "725 EAST CHESTNUT STREET",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.4998394",
      "longitude": "-84.73087635",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/mur.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ADM"
    },
    {
      "buildingCode": "CAB",
      "buildingName": "Nellie Craig Walker Hall",
      "buildingAddress": "301 SOUTH CAMPUS AVENUE",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50645984",
      "longitude": "-84.73889024",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/cab.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ADM"
    },
    {
      "buildingCode": "BOY",
      "buildingName": "Boyd Hall",
      "buildingAddress": "551 WESTERN COLLEGE DRIVE",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50350176",
      "longitude": "-84.72542676",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/boy.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "HUG",
      "buildingName": "Hughes Laboratories",
      "buildingAddress": "5357 BONHAM ROAD",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50967632",
      "longitude": "-84.73180131",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/hug.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "HYT",
      "buildingName": "Hoyt Hall",
      "buildingAddress": "521 PATTERSON AVENUE",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50320931",
      "longitude": "-84.72780135",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/hyt.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ADM"
    },
    {
      "buildingCode": "MCB",
      "buildingName": "McBride Hall",
      "buildingAddress": "McBride Hall, Miami University, 11 N Fisher Drive",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.51066377",
      "longitude": "-84.72701972",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/mcb.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "FNK",
      "buildingName": "Dave Finkleman Auditorium",
      "buildingAddress": "4200 North University Boulevard Building",
      "buildingCity": "Middletown",
      "buildingZip": "45042",
      "buildingState": null,
      "campusCode": "M",
      "latitude": "39.525271",
      "longitude": "-84.35619",
      "iconURL": null,
      "imageURL": null,
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "JHN",
      "buildingName": "Johnston Hall",
      "buildingAddress": "4200 North University Boulevard Building",
      "buildingCity": "Middletown",
      "buildingZip": "45042",
      "buildingState": null,
      "campusCode": "M",
      "latitude": "39.523972",
      "longitude": "-84.357641",
      "iconURL": null,
      "imageURL": null,
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "SWG",
      "buildingName": "Swing Hall",
      "buildingAddress": "Swing Hall, Miami University, 105 Tallawanda Road",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.51143505",
      "longitude": "-84.73413983",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/swg.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "RIC",
      "buildingName": "Richard Hall",
      "buildingAddress": "Richard Hall, Miami University, 501 South Oak Street",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50445486",
      "longitude": "-84.73559553",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/ric.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "HNE",
      "buildingName": "Hahne Hall",
      "buildingAddress": "Hahne Hall, Miami University, 5357 Bonham Road",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.51531285",
      "longitude": "-84.73222007",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/hne.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "ELT",
      "buildingName": "Elliott Hall",
      "buildingAddress": "Elliott Hall, Miami University, 101 Irvin Drive",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50903217",
      "longitude": "-84.73527276",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/elt.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "SCT",
      "buildingName": "Scott Hall",
      "buildingAddress": "Scott Hall, Miami University, 500 S Maple Avenue",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50439364",
      "longitude": "-84.73369052",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/sct.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "SDC",
      "buildingName": "Student Athlete Development",
      "buildingAddress": "NA",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.51763338",
      "longitude": "-84.73299576",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/sdc.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ATH"
    },
    {
      "buildingCode": "MCC",
      "buildingName": "Marcum Conference Center",
      "buildingAddress": "351 NORTH FISHER DRIVE",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.5129528",
      "longitude": "-84.72769977",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/mcc.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "CUL"
    },
    {
      "buildingCode": "RDB",
      "buildingName": "Roudebush Hall",
      "buildingAddress": "501 EAST HIGH STREET",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50946254",
      "longitude": "-84.73451048",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/rdb.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ADM"
    },
    {
      "buildingCode": "SHC",
      "buildingName": "Shriver Center",
      "buildingAddress": "701 EAST SPRING STREET",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50664067",
      "longitude": "-84.73182926",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/shc.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ADM"
    },
    {
      "buildingCode": "PSC",
      "buildingName": "Police Services Center",
      "buildingAddress": "4945 OXFORD TRENTON ROAD",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50730235",
      "longitude": "-84.72086632",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/psc.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ADM"
    },
    {
      "buildingCode": "IRV",
      "buildingName": "Irvin Hall",
      "buildingAddress": "400 EAST SPRING STREET",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.5079161",
      "longitude": "-84.73554819",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/irv.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "SHD",
      "buildingName": "Shideler Hall",
      "buildingAddress": "250 SOUTH PATTERSON AVENUE",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50770154",
      "longitude": "-84.73135672",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/shd.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "PRS",
      "buildingName": "Presser Hall",
      "buildingAddress": "501 SOUTH PATTERSON AVENUE",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50380032",
      "longitude": "-84.72967685",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/prs.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "PBD",
      "buildingName": "Peabody Hall",
      "buildingAddress": "Peabody Hall, Miami University, 701 Western College Drive",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50128874",
      "longitude": "-84.72579122",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/pbd.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "GYM",
      "buildingName": "Gymnasium",
      "buildingAddress": null,
      "buildingCity": null,
      "buildingZip": "45011",
      "buildingState": null,
      "campusCode": "H",
      "latitude": "39.376731",
      "longitude": "-84.563838",
      "iconURL": null,
      "imageURL": null,
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ATH"
    },
    {
      "buildingCode": "CLW",
      "buildingName": "Clawson Hall",
      "buildingAddress": "Clawson Hall, Miami University, 440 Western College Drive",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.5041805",
      "longitude": "-84.7263712",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/clw.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "AND",
      "buildingName": "Anderson Hall",
      "buildingAddress": "Anderson Hall, Miami University, 701 South Oak Street",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50212052",
      "longitude": "-84.73564133",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/and.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "EMR",
      "buildingName": "Emerson Hall",
      "buildingAddress": "Emerson Hall, Miami University, 699 Maple Avenue",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50175911",
      "longitude": "-84.73200013",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/emr.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "EDH",
      "buildingName": "Erickson Dining Hall",
      "buildingAddress": "23 NORTH FISHER DRIVE",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.51114489",
      "longitude": "-84.72579071",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/edh.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "HAR",
      "buildingName": "Harris Dining Hall",
      "buildingAddress": "500 HARRIS DRIVE",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50199183",
      "longitude": "-84.73468239",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/har.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "SCH",
      "buildingName": "Schwarm Hall",
      "buildingAddress": null,
      "buildingCity": null,
      "buildingZip": "45011",
      "buildingState": null,
      "campusCode": "H",
      "latitude": "39.378091",
      "longitude": "-84.562283",
      "iconURL": null,
      "imageURL": null,
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "RBD",
      "buildingName": "Regional Bank Depository",
      "buildingAddress": "4200 North University Boulevard Building",
      "buildingCity": "Middletown",
      "buildingZip": "45042",
      "buildingState": null,
      "campusCode": "M",
      "latitude": "39.525718",
      "longitude": "-84.35836",
      "iconURL": null,
      "imageURL": null,
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ADM"
    },
    {
      "buildingCode": "SHC",
      "buildingName": "Shriver Center",
      "buildingAddress": "701 EAST SPRING STREET",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50664067",
      "longitude": "-84.73182926",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/shc.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "DIN"
    },
    {
      "buildingCode": "MAR",
      "buildingName": "Martin Dining Hall",
      "buildingAddress": "5397 BONHAM ROAD",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.51526563",
      "longitude": "-84.73330418",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/mar.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "DIN"
    },
    {
      "buildingCode": "COK",
      "buildingName": "Cook Place",
      "buildingAddress": "51 SOUTH FISHER DRIVE",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50936773",
      "longitude": "-84.72706077",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/cok.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ADM"
    },
    {
      "buildingCode": "GAS",
      "buildingName": "Gaskill Hall",
      "buildingAddress": "540 EAST SPRING STREET",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50800838",
      "longitude": "-84.73369139",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/gas.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "ICE",
      "buildingName": "Goggin Ice Arena",
      "buildingAddress": "610 SOUTH OAK STREET",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50383517",
      "longitude": "-84.73700598",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/ice.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ATH"
    },
    {
      "buildingCode": "PHE",
      "buildingName": "Phelps Hall",
      "buildingAddress": null,
      "buildingCity": null,
      "buildingZip": "45011",
      "buildingState": null,
      "campusCode": "H",
      "latitude": "39.378165",
      "longitude": "-84.563903",
      "iconURL": null,
      "imageURL": null,
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "BIS",
      "buildingName": "Bishop Hall",
      "buildingAddress": "Bishop Hall, Miami University, 300 East Spring Street",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50796781",
      "longitude": "-84.73710797",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/bis.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "ROB",
      "buildingName": "Robertson Hall",
      "buildingAddress": "520 EAST SPRING STREET",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50788911",
      "longitude": "-84.73413522",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/rob.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ADM"
    },
    {
      "buildingCode": "MAR",
      "buildingName": "Martin Dining Hall",
      "buildingAddress": "5397 BONHAM ROAD",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.51526563",
      "longitude": "-84.73330418",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/mar.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "LNG",
      "buildingName": "Langstroth Cottage",
      "buildingAddress": "303 SOUTH PATTERSON AVENUE",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50667177",
      "longitude": "-84.73019823",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/lng.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ADM"
    },
    {
      "buildingCode": "CHP",
      "buildingName": "Sesquicentennial Chapel",
      "buildingAddress": "551 EAST SPRING STREET",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50687408",
      "longitude": "-84.73330726",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/chp.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "CUL"
    },
    {
      "buildingCode": "CUL",
      "buildingName": "Culler Hall",
      "buildingAddress": "620 EAST SPRING STREET",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50772777",
      "longitude": "-84.73251215",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/cul.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "CPA",
      "buildingName": "Center for Performing Arts",
      "buildingAddress": "420 SOUTH PATTERSON AVENUE",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50496654",
      "longitude": "-84.73191738",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/cpa.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "CUL"
    },
    {
      "buildingCode": "PSN",
      "buildingName": "Pearson Hall",
      "buildingAddress": "700 EAST HIGH STREET",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.51100519",
      "longitude": "-84.7313811",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/psn.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "PHI",
      "buildingName": "Phillips Hall",
      "buildingAddress": "420 SOUTH OAK STREET",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50535493",
      "longitude": "-84.7369802",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/phi.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "YWS",
      "buildingName": "Yager Stadium West",
      "buildingAddress": "NA",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.520191",
      "longitude": "-84.73153",
      "iconURL": null,
      "imageURL": null,
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ATH"
    },
    {
      "buildingCode": "BRN",
      "buildingName": "Brandon Hall",
      "buildingAddress": "Brandon Hall, Miami University, 385 Tallawanda Avenue",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.51472382",
      "longitude": "-84.73393265",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/brn.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "FLW",
      "buildingName": "Flower Hall",
      "buildingAddress": "Flower Hall, Miami University, 5347 Bonham Road",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.5160459",
      "longitude": "-84.73282437",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/flw.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "HEP",
      "buildingName": "Hepburn Hall",
      "buildingAddress": "Hepburn Hall, Miami University, 355 Tallawanda Road",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.51436823",
      "longitude": "-84.73319542",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/hep.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "HSC",
      "buildingName": "Health Services Center",
      "buildingAddress": "421 SOUTH CAMPUS AVENUE",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50462197",
      "longitude": "-84.7386531",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/hsc.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ADM"
    },
    {
      "buildingCode": "FSB",
      "buildingName": "Farmer School of Business",
      "buildingAddress": "800 EAST HIGH STREET",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.51127649",
      "longitude": "-84.72968946",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/fsb.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ACA"
    },
    {
      "buildingCode": "HAR",
      "buildingName": "Harris Dining Hall",
      "buildingAddress": "500 HARRIS DRIVE",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50199183",
      "longitude": "-84.73468239",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/har.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "DIN"
    },
    {
      "buildingCode": "CSB",
      "buildingName": "Cole Service Building",
      "buildingAddress": "101 SOUTH FISHER DRIVE",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50825466",
      "longitude": "-84.7273178",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/csb.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ADM"
    },
    {
      "buildingCode": "JOY",
      "buildingName": "Joyner House",
      "buildingAddress": "321 EAST SPRING STREET",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50702887",
      "longitude": "-84.73709826",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/joy.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ADM"
    },
    {
      "buildingCode": "MMH",
      "buildingName": "MacMillan Hall",
      "buildingAddress": "531 EAST SPRING STREET",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50685526",
      "longitude": "-84.73395827",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/mmh.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ADM"
    },
    {
      "buildingCode": "MAC",
      "buildingName": "MacCracken Hall",
      "buildingAddress": "MacCracken Hall, Miami University, 501 Center Drive",
      "buildingCity": "Oxford",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50413889",
      "longitude": "-84.73466777",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/mac.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "RES"
    },
    {
      "buildingCode": "PAT",
      "buildingName": "Patterson Place",
      "buildingAddress": "301 SOUTH PATTERSON AVENUE",
      "buildingCity": "OXFORD",
      "buildingZip": "45056",
      "buildingState": "OH",
      "campusCode": "O",
      "latitude": "39.50536627",
      "longitude": "-84.72947678",
      "iconURL": null,
      "imageURL": "http://community.miamioh.edu/location/images/pat.jpg",
      "parentResource": null,
      "phoneNumber": null,
      "website": null,
      "wifi": "Y",
      "functionCode": "ADM"
    }
  ],
  "status": 200,
  "error": false
}